[project]
name = "proyecto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mysql>=0.0.3",
    "mysql-connector-python>=9.2.0",
    "streamlit>=1.43.2",
]
